// JsFromRoutes CacheKey 429412bd19f074d71718c7939b3b7ac2
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { request } from '~/services/ApiService'

export default {
  list: options =>
    request('get', '/video_clips/:video_clip_id/comments', options),

  get: options =>
    request('get', '/comments/:id', options),
}
