// JsFromRoutes CacheKey 465dadd776019492e8193d86b671ea5e
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { request } from '@services/ApiService'

export default {
  list: options =>
    request('get', '/video_clips/:video_clip_id/comments', options),

  get: options =>
    request('get', '/comments/:id', options),
}
