// JsFromRoutes CacheKey 8593666cc8047eab399e3376f017720c
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { formatUrl } from '@helpers/UrlHelper'
import { request } from '@services/ApiService'

export default {
  switchToClassicNavbar: options =>
    request('patch', '/user_preferences/switch_to_classic_navbar', options),

  switchToClassicPath: options =>
    formatUrl('/user_preferences/switch_to_classic/:page', options),

  switchToBetaPath: options =>
    formatUrl('/user_preferences/switch_to_beta/:page', options),
}
