// JsFromRoutes CacheKey a122aff0f348f7f65b97537d3ab05f79
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  switchToClassicNavbar: definePathHelper('patch', '/user_preferences/switch_to_classic_navbar'),
  switchToClassic: definePathHelper('get', '/user_preferences/switch_to_classic/:page'),
  switchToBeta: definePathHelper('get', '/user_preferences/switch_to_beta/:page'),
}
