// JsFromRoutes CacheKey d49f49874e7d05e812a509bfbd1d83bc
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  switchToClassicNavbar: /* #__PURE__ */ definePathHelper('patch', '/user_preferences/switch_to_classic_navbar'),
  switchToClassic: /* #__PURE__ */ definePathHelper('get', '/user_preferences/switch_to_classic/:page'),
  switchToBeta: /* #__PURE__ */ definePathHelper('get', '/user_preferences/switch_to_beta/:page'),
}
