// JsFromRoutes CacheKey ad45663323f4c6da5ccdfbe4de75c005
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  switchToClassicNavbar: /* #__PURE__ */ definePathHelper('patch', '/user_preferences/switch_to_classic_navbar'),
  switchToClassic: /* #__PURE__ */ definePathHelper('get', '/user_preferences/switch_to_classic/:page'),
  switchToBeta: /* #__PURE__ */ definePathHelper('get', '/user_preferences/switch_to_beta/:page'),
}
