fix: true
ignore:
  - 'packages/**/*'
  - 'scripts/**/*'
  - 'playground/**/*'
  - '**/*':
    - Style/TrailingCommaInArrayLiteral
    - Style/TrailingCommaInHashLiteral
    - Style/TrailingCommaInArguments
