// JsFromRoutes CacheKey 7097596b2ac2a8f17da030d35d651b76
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { request } from '@js-from-routes/core'

export default {
  list: options =>
    request('get', '/video_clips/:video_clip_id/comments', options),

  get: options =>
    request('get', '/comments/:id', options),
}
