// JsFromRoutes CacheKey b6d8519c6402b2a4bdccf3e35abfc973
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { pathFor, request } from '@js-from-routes/client'

export default {
  pathFor,

  list: options =>
    request('get', '/video_clips/:video_clip_id/comments', options),

  get: options =>
    request('get', '/comments/:id', options),
}
