// JsFromRoutes CacheKey e72f6242839b7956fa1f12ec3dbaceee
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { formatUrl } from '@js-from-routes/core'
import { request } from '@js-from-routes/core'

export default {
  switchToClassicNavbar: options =>
    request('patch', '/user_preferences/switch_to_classic_navbar', options),

  switchToClassicPath: options =>
    formatUrl('/user_preferences/switch_to_classic/:page', options),

  switchToBetaPath: options =>
    formatUrl('/user_preferences/switch_to_beta/:page', options),
}
