// JsFromRoutes CacheKey 0d876d881de5f62510a1969485b11842
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { formatUrl, pathFor, request } from '@js-from-routes/client'

export default {
  pathFor,

  switchToClassicNavbar: options =>
    request('patch', '/user_preferences/switch_to_classic_navbar', options),

  switchToClassicPath: options =>
    formatUrl('/user_preferences/switch_to_classic/:page', options),

  switchToBetaPath: options =>
    formatUrl('/user_preferences/switch_to_beta/:page', options),
}
