// JsFromRoutes CacheKey 60215ea725cd251f2e5697253677f531
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { formatUrl, pathFor, request } from '@js-from-routes/client'

export default {
  pathFor,

  downloadPath: options =>
    formatUrl('/video_clips/:id/download', options),

  addToPlaylist: options =>
    request('patch', '/video_clips/:id/add_to_playlist', options),

  removeFromPlaylist: options =>
    request('patch', '/video_clips/:id/remove_from_playlist', options),

  latest: options =>
    request('get', '/video_clips/latest', options),

  thumbnail: options =>
    request('get', '/video_clips/:id/thumbnail/:thumbnail_id', options),

  create: options =>
    request('post', '/video_clips', options),

  new: options =>
    request('get', '/video_clips/new', options),

  edit: options =>
    request('get', '/video_clips/:id/edit', options),

  update: options =>
    request('patch', '/video_clips/:id', options),

  destroy: options =>
    request('delete', '/video_clips/:id', options),
}
