blank_issues_enabled: false
contact_links:
  - name: Troubleshooting & FAQs
    url: https://js-from-routes.netlify.app/faqs/
    about: 'Please check the most common problems before opening an issue'
  - name: Questions & Discussions
    url: https://github.com/ElMassimo/js_from_routes/discussions
    about: Use GitHub discussions for message-board style questions and discussions.
