source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.2"

gem "js_from_routes", path: "../../js_from_routes"

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem "rails", "~> 6.0.3", ">= 6.0.3.2"

# Use Puma as the app server
gem "puma", "~> 4.1"

# Use Vite.js as the frontend tool. Read more: https://github.com/ElMassimo/vite_ruby
gem "vite_rails"

group :development do
  gem "listen", "~> 3.2"
  gem "pry-byebug"
end
