// JsFromRoutes CacheKey b26802dc34a717e44348ce2bb8093b9a
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
export { default as videoClips } from '~/api/VideoClipsApi'
export { default as comments } from '~/api/CommentsApi'
export { default as userPreferences } from '~/api/UserPreferencesApi'
