// JsFromRoutes CacheKey 36ef1fc18097bf50aeeb62b4edd51579
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/video_clips/:video_clip_id/comments'),
  get: definePathHelper('get', '/comments/:id'),
}
