// JsFromRoutes CacheKey 8ce79f068ef4bbe871f1d544eb49cc85
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: definePathHelper('get', '/video_clips/:video_clip_id/comments'),
  show: definePathHelper('get', '/comments/:id'),
}
