// JsFromRoutes CacheKey 09e644b318ebab8c52c784b76a90159d
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  list: definePathHelper('get', '/video_clips/:video_clip_id/comments'),
  get: definePathHelper('get', '/comments/:id'),
}
