// JsFromRoutes CacheKey cd355b506c14e194db573527b71a3fc5
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/cs/:custom_section_slug/discussions'),
  create: /* #__PURE__ */ definePathHelper('post', '/cs/:custom_section_slug/discussions'),
  new: /* #__PURE__ */ definePathHelper('get', '/cs/:custom_section_slug/discussions/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/cs/:custom_section_slug/discussions/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/cs/:custom_section_slug/discussions/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/cs/:custom_section_slug/discussions/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/cs/:custom_section_slug/discussions/:id'),
}
