// JsFromRoutes CacheKey 561646920de8f6a6bbb5bba2640e3b53
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/s/:section_slug/discussions'),
  create: /* #__PURE__ */ definePathHelper('post', '/s/:section_slug/discussions'),
  new: /* #__PURE__ */ definePathHelper('get', '/s/:section_slug/discussions/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/s/:section_slug/discussions/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/s/:section_slug/discussions/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/s/:section_slug/discussions/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/s/:section_slug/discussions/:id'),
}
