// JsFromRoutes CacheKey 2cb57ad162dd9bedfd3bf49d31712cf1
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  index: /* #__PURE__ */ definePathHelper('get', '/s/:section_slug/discussions'),
  customSection: /* #__PURE__ */ definePathHelper('get', '/cs/:custom_section_slug/discussions'),
  create: /* #__PURE__ */ definePathHelper('post', '/s/:section_slug/discussions'),
  createPost: /* #__PURE__ */ definePathHelper('post', '/cs/:custom_section_slug/discussions'),
  new: /* #__PURE__ */ definePathHelper('get', '/s/:section_slug/discussions/new'),
  newCustomSectionDiscussion: /* #__PURE__ */ definePathHelper('get', '/cs/:custom_section_slug/discussions/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/s/:section_slug/discussions/:id/edit'),
  editCustomSectionDiscussion: /* #__PURE__ */ definePathHelper('get', '/cs/:custom_section_slug/discussions/:id/edit'),
  show: /* #__PURE__ */ definePathHelper('get', '/s/:section_slug/discussions/:id'),
  customSectionDiscussion: /* #__PURE__ */ definePathHelper('get', '/cs/:custom_section_slug/discussions/:id'),
  update: /* #__PURE__ */ definePathHelper('patch', '/s/:section_slug/discussions/:id'),
  updatePatch: /* #__PURE__ */ definePathHelper('patch', '/cs/:custom_section_slug/discussions/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/s/:section_slug/discussions/:id'),
  destroyDelete: /* #__PURE__ */ definePathHelper('delete', '/cs/:custom_section_slug/discussions/:id'),
}
