// JsFromRoutes CacheKey ca8b1d775abee75d7fdfa6a7f25d82fe
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import videoClips from '~/api/VideoClipsApi'
import comments from '~/api/CommentsApi'
import userPreferences from '~/api/UserPreferencesApi'

export default {
  videoClips,
  comments,
  userPreferences,
}
