// JsFromRoutes CacheKey 7a29896fdf5859978288e03802ba8f24
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  switchToClassicNavbar: definePathHelper('patch', '/user_preferences/switch_to_classic_navbar'),
  switchToClassic: definePathHelper('get', '/user_preferences/switch_to_classic/:page'),
  switchToBeta: definePathHelper('get', '/user_preferences/switch_to_beta/:page'),
}
