// JsFromRoutes CacheKey a8720dc83b2045fba3cbd744f27f5209
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/redaxios'

export default {
  switchToClassicNavbar: definePathHelper('patch', '/user_preferences/switch_to_classic_navbar'),
  switchToClassic: definePathHelper('get', '/user_preferences/switch_to_classic/:page'),
  switchToBeta: definePathHelper('get', '/user_preferences/switch_to_beta/:page'),
}
