// JsFromRoutes CacheKey dc8ac27406e4ff267ab4b0ef6e395f80
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  download: definePathHelper('get', '/video_clips/:id/download'),
  addToPlaylist: definePathHelper('patch', '/video_clips/:id/add_to_playlist'),
  removeFromPlaylist: definePathHelper('patch', '/video_clips/:id/remove_from_playlist'),
  latest: definePathHelper('get', '/video_clips/latest'),
  thumbnail: definePathHelper('get', '/video_clips/:id/thumbnail/:thumbnail_id'),
  create: definePathHelper('post', '/video_clips'),
  new: definePathHelper('get', '/video_clips/new'),
  edit: definePathHelper('get', '/video_clips/:id/edit'),
  update: definePathHelper('patch', '/video_clips/:id'),
  destroy: definePathHelper('delete', '/video_clips/:id'),
}
