// JsFromRoutes CacheKey 932961009743a2c9330efd16b43845e8
//
// DO NOT MODIFY: This file was automatically generated by JsFromRoutes.
import { definePathHelper } from '@js-from-routes/client'

export default {
  download: /* #__PURE__ */ definePathHelper('get', '/video_clips/:id/download'),
  addToPlaylist: /* #__PURE__ */ definePathHelper('patch', '/video_clips/:id/add_to_playlist'),
  removeFromPlaylist: /* #__PURE__ */ definePathHelper('patch', '/video_clips/:id/remove_from_playlist'),
  latest: /* #__PURE__ */ definePathHelper('get', '/video_clips/latest'),
  thumbnail: /* #__PURE__ */ definePathHelper('get', '/video_clips/:id/thumbnail/:thumbnail_id'),
  create: /* #__PURE__ */ definePathHelper('post', '/video_clips'),
  new: /* #__PURE__ */ definePathHelper('get', '/video_clips/new'),
  edit: /* #__PURE__ */ definePathHelper('get', '/video_clips/:id/edit'),
  update: /* #__PURE__ */ definePathHelper('patch', '/video_clips/:id'),
  destroy: /* #__PURE__ */ definePathHelper('delete', '/video_clips/:id'),
}
