name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: build
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' || matrix.experimental }}
    env:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 3
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        ruby: [
          3.0,
          3.2
        ]
        gemfile: [
          "gemfiles/Gemfile-rails.6.1.x",
          "gemfiles/Gemfile-rails.7.0.x"
        ]
        experimental: [false]
        include:
          - ruby: "3.2"
            os: ubuntu-latest
            gemfile: gemfiles/Gemfile-rails-edge
            experimental: true

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Setup Code Climate test-reporter
        if: ${{ contains(github.ref, 'main') }}
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          chmod +x ./cc-test-reporter
          ./cc-test-reporter before-build

      - name: Ruby specs
        run: bundle exec rspec

      - name: Upload code coverage to Code Climate
        if: ${{ contains(github.ref, 'main') }}
        run: |
          export GIT_BRANCH="${GITHUB_REF/refs\/heads\//}"
          ./cc-test-reporter after-build -r ${{secrets.CC_TEST_REPORTER_ID}}
